### ISSUE TITLE
sonar-housekeeper never exits

### ISSUE THREAD

**Issue by jblaine** [okorach/sonar-tools#872] opened 2023-05-23 21:19 UTC
Using sonar-tools 2.6, I am not yet able to get sonar-housekeeper to complete:

```
sonar-housekeeper -t mytokenhere -B 300 -R 300 -T 300 --mode delete --url https://sonarqube.our.com
<lots of lines of output>
<output stops after a 5-10 seconds>
<after waiting hours, I hit Ctrl-C>
^C
Traceback (most recent call last):
  File "/home/jblaine/testenv/bin/sonar-housekeeper", line 8, in <module>
    sys.exit(main())
  File "/home/jblaine/testenv/lib/python3.9/site-packages/tools/housekeeper.py", line 209, in main
    problems = get_project_problems(args.projects, args.branches, args.pullrequests, args.threads, sq)
  File "/home/jblaine/testenv/lib/python3.9/site-packages/tools/housekeeper.py", line 53, in get_project_problems
    problems = projects.audit(endpoint=endpoint, audit_settings=settings)
  File "/home/jblaine/testenv/lib/python3.9/site-packages/sonar/projects/projects.py", line 1141, in audit
    q.join()
  File "/home/jblaine/python/lib/python3.9/queue.py", line 90, in join
    self.all_tasks_done.wait()
  File "/home/jblaine/python/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by okorach** [comment] 2023-05-28 09:33
Hello @jblaine ,

Thanks for reporting the problem. I will look into it.
In the mean time, can you check if the following workaround helps: pass `--threads 1` on the command line.
The execution may be longer (it depends on the number of projects on your platform) but it may help completing the tool successfully. Let me know if that works.
`sonar-housekeeper -t mytokenhere -B 300 -R 300 -T 300 --mode delete --url https://sonarqube.our.com --threads 1`

Also, could you please send me the output of the execution without the `--threads` parameter in debug mode. You may obfuscate the logs if you want (SonarQube URL, project names...)
`sonar-housekeeper -t mytokenhere -B 300 -R 300 -T 300 --mode delete --url https://sonarqube.our.com -v DEBUG`

**Comment by okorach** [comment] 2023-05-28 09:42
Problem possibly due to #874

**Comment by okorach** [comment] 2023-05-29 12:29
Hello @jblaine,
Could you let me know which version and edition of SonarQube you use.
If that it the latest 10.0 then I think i understand the problem. The SonarQube API changed making sonar tools incompatible, see #886

**Comment by okorach** [comment] 2023-05-29 14:29
Hello @jblaine,

I have released sonar-tools 2.7 that should fix your problem. Please let me know so that I can close the issue... or not

**Comment by okorach** [comment] 2023-06-14 17:08
Hello @jblaine,

Thanks for the new stack trace. This is a plain mistake on my side that my regression tests could not find (because I don't have at hand a platform with branches (i.e. a developer edition, an enterprise edition or a datacenter edition).

Before I release again (I am wary of missing something again), could you check this beta attached.
[sonar_tools-2.7.1-py3-none-any.whl.gz](https://github.com/okorach/sonar-tools/files/11748743/sonar_tools-2.7.1-py3-none-any.whl.gz)

The way to install is:
- `Remove previous version 2.7 of sonar-tools: `pip uninstall sonar-tools`
- Unzip the above: `gunzip sonar_tools-2.7.1-py3-none-any.whl.gz`
- Install the unzipped file with the following command: `python3 -m pip install sonar_tools-2.7.1-py3-none-any.whl`

Then try `sonar-housekeeper` again. Let me know if it works. If all good I will make an official patch release.

**Comment by jblaine** [comment] 2023-06-16 13:49
The updated code worked fine for me. Thanks! Note, however, that I did not get a chance to test it until after we had upgraded to Sonarqube 9.9 LTS this week. So whether it works or not with 8.9 LTS, I cannot say.

**Comment by okorach** [comment] 2023-06-17 07:07
Thanks @jblaine .
I understand that you verified after upgrading to SonarQube 9.9 which is the new LTS.
That's the most important part (compatibility with SonarQube LTS) although I will try to keep backwards compatibility with the old LTS (8.9) for a while.
I will not release immediately as I have seen that you have opened a new issue #890.
I will fix that one too before releasing.

**Closed** 2023-06-17 07:32 UTC
